version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/nanduv-portfolio"
      - "/nanduv-portfolio/node_modules"
    ports:
      - 3000:3000
    command: ["npm", "start"]